spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=60s
  application:
    name: BootCamp Sysmap 2024 - Sameque Ananias

server:
  servlet:
    context-path: /api
  port: 8082
logging:
  level:
    org:
      springframework:
        security: DEBUG